= JBang Utilities

This is a small repository which holds some https://jbang.dev[JBang] utilities.

All commands listed will have a hidden `generate-completion` sub-command for auto-completion in bash or ZSH.

== Commands

=== `parse-surefire-report`

This simple utility parses a surefire and failsafe reports and by default just outputs some totals.

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install parse-surefire-report@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh parse-surefire-report@jamezp
----

==== Usage

[source,bash]
----
parse-surefire-report testsuite/
----

.Example Output
[source,bash]
----
*******************************************************************
Total: 2796 - PASSED: 2666 - FAILED: 0 - ERRORS: 0 - SKIPPED: 130
*******************************************************************
Completed in 00m, 00s, 344ms
----

=== `jdk-manager`

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install jdk-manager@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh jdk-manager@jamezp
----

==== Usage

Listing the available JDK's for download:
[source,bash]
----
jdk-manager list
LTS Versions
  8
  11
  17
 *21
Versions
  8
  11
  16
  17
  18
  19
  20
  21
----

Listing locally installed JDK's from this tool:
----
jdk-manager list --local
Eclipse Adoptium 17.0.8.1 (2023-08-24): /home/jperkins/.jdk-manager/jdk-17
Eclipse Adoptium 20.0.2 (2023-07-18): /home/jperkins/.jdk-manager/jdk-20
Eclipse Adoptium 11.0.20.1 (2023-08-24): /home/jperkins/.jdk-manager/jdk-11
Temurin 1.8.0_382 (null): /home/jperkins/.jdk-manager/jdk-8
Eclipse Adoptium 22-beta (2024-03-19): /home/jperkins/.jdk-manager/jdk-22
Eclipse Adoptium 21 (2023-09-19): /home/jperkins/.jdk-manager/jdk-21
----

Installing a JDK
[source,bash]
----
jdk-manager install 21
----

Setting the `JAVA_HOME` based on the result of a local JDK.
[source,bash]
----
export JAVA_HOME="$(jdk-manager info -d -p java.home 21)"
----

=== `echo-server`

This simple utility creates a server socket and echos the data received to `stdout`.

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install echo-server@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh echo-server@jamezp
----

==== Usage

[source,bash]
----
echo-server --tcp -p 9514
echo-server --http -p 8080
----
