= JBang Utilities

This is a small repository which holds some https://jbang.dev[JBang] utilities.

All commands listed will have a hidden `generate-completion` sub-command for auto-completion in bash or ZSH.

== Commands

=== `parse-surefire-report`

This simple utility parses a surefire and failsafe reports and by default just outputs some totals.

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install parse-surefire-report@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh parse-surefire-report@jamezp
----

==== Usage

[source,bash]
----
parse-surefire-report testsuite/
----

.Example Output
[source,bash]
----
*******************************************************************
Total: 2796 - PASSED: 2666 - FAILED: 0 - ERRORS: 0 - SKIPPED: 130
*******************************************************************
Completed in 00m, 00s, 344ms
----

=== `jdk-manager`

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install jdk-manager@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh jdk-manager@jamezp
----

==== Usage

Listing the available JDK's for download:
[source,bash]
----
jdk-manager list
LTS Versions for temurin
  8
  11
  17
 *21
STS Versions for temurin
  16
  18
  19
  20
  22
  23
  24
Early Access Versions for temurin
  24
  25
----

Listing locally installed JDK's from this tool:
----
jdk-manager list --local
IBM Corporation 23.0.1 (2024-10-15): /home/jperkins/.jdk-manager/semeru/jdk-23
Eclipse Adoptium 17.0.13 (2024-10-15): /home/jperkins/.jdk-manager/temurin/jdk-17
Eclipse Adoptium 21.0.5 (2024-10-15): /home/jperkins/.jdk-manager/temurin/jdk-21
Eclipse Adoptium 23.0.1 (2024-10-15): /home/jperkins/.jdk-manager/temurin/jdk-23
Eclipse Adoptium 24-beta (2025-03-18): /home/jperkins/.jdk-manager/temurin/jdk-24
Eclipse Adoptium 25-beta (2025-09-16): /home/jperkins/.jdk-manager/temurin/jdk-25
Temurin 1.8.0_432 (null): /home/jperkins/.jdk-manager/temurin/jdk-8
----

Installing a JDK
[source,bash]
----
jdk-manager install 21
----

Setting the `JAVA_HOME` based on the result of a local JDK.
[source,bash]
----
export JAVA_HOME="$(jdk-manager info -d -p java.home 21)"
----

=== `echo-server`

This simple utility creates a server socket and echos the data received to `stdout`.

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install echo-server@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh echo-server@jamezp
----

==== Usage

[source,bash]
----
echo-server --tcp -p 9514
echo-server --http -p 8080
----

=== `jira-from-pr`

This is a utility, specifically designed for Red Hat JIRA, which creates a JIRA based on a GitHub Pull Request. It is
useful when there is a need to create a JIRA for a dependabot pull request.

It requires two files be present on your local file system in your home directory, preferably with 0600 permissions on
the files:

1. `.github`
2. `.jira`

The `.github` file must have an entry for `oatuh` where the value is simply a GitHub token. This file and property name
is adopted from https://hub4j.github.io/github-api/.

The `.jira` file must have the following two properties:

1. `username` where the value is your JIRA username
2. `token` where the value is a token you must create for your JIRA user.

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install jira-from-pr@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh jira-from-pr@jamezp
----

==== Usage

There are 3 required parameters:


|===
|Argument |Description

|`-o`, `--organization`
|The GitHub organization where the pull request is located.

|`-r`, `--repository`
|The GitHub repository where the pull request is located.

|`-p`, `--project`
|The JIRA project at https://issues.redhat.com
|===

[source,bash]
----
jira-from-pr -o resteasy -r resteasy -p RESTEASY 4686
----

For details on additional parameters execute:
[source,bash]
----
jira-from-pr -h
----


=== `zip-util`

This is a simple utility that allows you to query archive files. It allows you to recursively inspect files. This can
be useful for things like WAR's where there may be embedded JAR's you want to see the contents of.

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install zip-util@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh zip-util@jamezp
----

==== Usage

[source,bash]
----
zip-util -r my.war
zip-util -e "{arquillian*}.jar" -r my-test.ear
----