= JBang Utilities

This is a small repository which holds some https://jbang.dev[JBang] utilities.

All commands listed will have a hidden `generate-completion` sub-command for auto-completion in bash or ZSH.

== Commands

=== `parse-surefire-report`

This simple utility parses a surefire and failsafe reports and by default just outputs some totals.

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install parse-surefire-report@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh parse-surefire-report@jamezp
----

==== Usage

[source,bash]
----
parse-surefire-report testsuite/
----

.Example Output
[source,bash]
----
*******************************************************************
Total: 2796 - PASSED: 2666 - FAILED: 0 - ERRORS: 0 - SKIPPED: 130
*******************************************************************
Completed in 00m, 00s, 344ms
----

=== `jdk-manager`

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install jdk-manager@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh jdk-manager@jamezp
----

==== Usage

Listing the available JDK's for download:
[source,bash]
----
jdk-manager list
LTS Versions for temurin
  8
  11
  17
 *21
STS Versions for temurin
  16
  18
  19
  20
  22
  23
  24
Early Access Versions for temurin
  24
  25
----

Listing locally installed JDK's from this tool:
----
jdk-manager list --local
IBM Corporation 23.0.1 (2024-10-15): /home/jperkins/.jdk-manager/semeru/jdk-23
Eclipse Adoptium 17.0.13 (2024-10-15): /home/jperkins/.jdk-manager/temurin/jdk-17
Eclipse Adoptium 21.0.5 (2024-10-15): /home/jperkins/.jdk-manager/temurin/jdk-21
Eclipse Adoptium 23.0.1 (2024-10-15): /home/jperkins/.jdk-manager/temurin/jdk-23
Eclipse Adoptium 24-beta (2025-03-18): /home/jperkins/.jdk-manager/temurin/jdk-24
Eclipse Adoptium 25-beta (2025-09-16): /home/jperkins/.jdk-manager/temurin/jdk-25
Temurin 1.8.0_432 (null): /home/jperkins/.jdk-manager/temurin/jdk-8
----

Installing a JDK
[source,bash]
----
jdk-manager install 21
----

Setting the `JAVA_HOME` based on the result of a local JDK.
[source,bash]
----
export JAVA_HOME="$(jdk-manager info -d -p java.home 21)"
----

=== `echo-server`

This simple utility creates a server socket and echos the data received to `stdout`.

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install echo-server@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh echo-server@jamezp
----

==== Usage

[source,bash]
----
echo-server --tcp -p 9514
echo-server --http -p 8080
----

=== `zip-util`

This is a simple utility that allows you to query archive files. It allows you to recursively inspect files. This can
be useful for things like WAR's where there may be embedded JAR's you want to see the contents of.

==== Installation

The simplest way to install the command is with the https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html[JBang Alias].

[source,bash]
----
jbang app install zip-util@jamezp
----

To update the application:

[source,bash]
----
jbang build --fresh zip-util@jamezp
----

==== Usage

[source,bash]
----
zip-util -r my.war
zip-util -e "{arquillian*}.jar" -r my-test.ear
----